name: sync rss with notion databases

on:
  schedule:
    - cron: 0 17 */3 * * # JST 0:00 (every 3 days)
  push:
    branches:
      - master
    paths:
      - 'cli/**'
  workflow_dispatch:

env:
  TZ: 'Asia/Tokyo'

jobs:
  batch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - uses: pnpm/action-setup@v4

      - name: install dependencies
        run: pnpm install

      - name: run batch
        run: |
          make cli-start-reset
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_FEEDER_DATASOURCE_ID: ${{ secrets.NOTION_FEEDER_DATASOURCE_ID }}
          NOTION_READER_DATASOURCE_ID: ${{ secrets.NOTION_READER_DATASOURCE_ID }}
          ENTRIES_JSON_OUTPUT: ../frontend/public/entries.json

      - name: build frontend
        run: make front-build

      - name: deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.dist
