name: sync rss with notion databases

on:
  schedule:
    - cron: 0 17 * * * # JST 0:00
  push:
    branches:
      - master
    paths:
      - 'cli/**'
  workflow_dispatch:

env:
  TZ: 'Asia/Tokyo'
jobs:
  batch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - uses: pnpm/action-setup@v4
      - run: make cli-ci
      - run: make cli-start-reset
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_FEEDER_DATASOURCE_ID: ${{ secrets.NOTION_FEEDER_DATASOURCE_ID }}
          NOTION_READER_DATASOURCE_ID: ${{ secrets.NOTION_READER_DATASOURCE_ID }}
