name: build deploy gh-pages front

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  TZ: 'Asia/Tokyo'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - uses: pnpm/action-setup@v4

      - name: install
        run: make front-ci
      
      - name: build
        run: make front-build
      
      - name: deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
