name: build deploy gh-pages front

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  TZ: 'Asia/Tokyo'

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - uses: pnpm/action-setup@v4
      - run: make front-ci

      - name: download entries.json
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: batch.yaml
          name: entries-json
          path: .dist/
          if_no_artifact_found: warn
      - run: make front-build
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: .dist/

  deploy:
    needs: build
    if: always() && needs.build.result != 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: download dist
        id: download-dist
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yaml
          name: frontend-dist
          path: .dist/
          if_no_artifact_found: warn
          search_artifacts: true

      - name: deploy to Github Pages
        if: steps.download-dist.outputs.found_artifact == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .dist
